Revert "Fix memory leak in GetStreamInfoListImpl"
This reverts commit 41258f7c613d72e9e8e8cf422a0d30365e6f47cc.
This commit breaks C++11 builds with the following error:

include/ROOT/RMakeUnique.hxx:28:64:
   error: invalid use of array with unspecified bounds