Fixes for Python 3.7
 * PyROOT_PyUnicode_AsString changed return type from char* to const char*
 * Using _PyObject_GC_TRACK results in linking error:
   undefined reference to `_PyGC_generation0'
   The python documentation says this about _PyObject_GC_TRACK:
   "A macro version of PyObject_GC_Track(). It should not be used for
   extension modules."
   So it should not be used. Calling PyObject_GC_Track instead avoids the
   undefined symbol. I also removed the #ifndef R__WIN32 since the
   comment indicates that this was added to avoid the same issue on
   windows. Calling PyObject_GC_Track instead of using the
   _PyObject_GC_TRACK macro should fix the undefined symbol probelem on
   windows too.